#Rubocop config to keep in line with our changes to the style guide
Encoding:
  Enabled: false

LineLength:
  Max: 200

CommentAnnotation:
  Enabled: false

Documentation:
  Enabled: false

Style/SpaceInsideStringInterpolation:
  EnforcedStyle: space

Style/NumericPredicate:
  Enabled: false

Metrics/MethodLength:
  Max: 15

Metrics/AbcSize:
  Max: 20
